
package com.github.soap2jms.service;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.github.soap2jms.common.ws.MessageIdAndStatus;
import com.github.soap2jms.common.ws.ObjectFactory;
import com.github.soap2jms.common.ws.WsJmsMessage;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "sender.soap2jms", targetNamespace = "http://soap2jms.github.com/service")
@XmlSeeAlso({ ObjectFactory.class })
public interface SenderSoap2Jms {

	/**
	 * 
	 * @param queueName
	 * @param messageSetIdentifier
	 * @param messages
	 * @return returns
	 *         java.util.List<com.github.soap2jms.common.ws.MessageIdAndStatus>
	 * @throws WsJmsException
	 */
	@WebMethod(action = "http://soap2jms.github.com/sendMessages")
	@WebResult(name = "messageIdAndStatus", targetNamespace = "")
	@RequestWrapper(localName = "sendMessages", targetNamespace = "http://soap2jms.github.com/common/ws", className = "com.github.soap2jms.common.ws.SendMessages")
	@ResponseWrapper(localName = "sendMessagesResponse", targetNamespace = "http://soap2jms.github.com/common/ws", className = "com.github.soap2jms.common.ws.WsJmsIdAndStatusList")
	public List<MessageIdAndStatus> sendMessages(@WebParam(name = "queueName", targetNamespace = "") String queueName,
			@WebParam(name = "messageSetIdentifier", targetNamespace = "") String messageSetIdentifier,
			@WebParam(name = "messages", targetNamespace = "") List<WsJmsMessage> messages) throws WsJmsException;

}
