
package com.github.soap2jms.service;

import javax.xml.ws.WebFault;

import com.github.soap2jms.common.StatusCodeEnum;
import com.github.soap2jms.common.WsExceptionClass;
import com.github.soap2jms.common.ws.WsJmsExceptionData;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebFault(name = "wsJmsException", targetNamespace = "http://soap2jms.github.com/common/ws")
public class WsJmsException extends Exception {

	/**
	 *
	 */
	private static final long serialVersionUID = -159443347422019950L;
	/**
	 * Java type that goes as soapenv:Fault detail element.
	 *
	 */
	private final WsJmsExceptionData faultInfo;

	/**
	 *
	 * @param faultInfo
	 * @param message
	 */
	public WsJmsException(final String message, final String originalException, final StatusCodeEnum code,
			final WsExceptionClass exceptionType) {
		super(message);
		this.faultInfo = new WsJmsExceptionData(message, originalException, code.getErrorCode(), null, exceptionType);
	}

	/**
	 *
	 * @param faultInfo
	 * @param message
	 */
	public WsJmsException(final String message, final WsJmsExceptionData faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 *
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public WsJmsException(final String message, final WsJmsExceptionData faultInfo, final Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 *
	 * @return returns fault bean:
	 *         com.github.soap2jms.common.ws.WsJmsExceptionData
	 */
	public WsJmsExceptionData getFaultInfo() {
		return this.faultInfo;
	}

}
