
package com.github.soap2jms.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "soapToJmsSenderService", targetNamespace = "http://soap2jms.github.com/service", wsdlLocation = "file:/usr/local/prj/misc/soap2jms/s2j_common/src/main/resources/queueSender.wsdl")
public class SoapToJmsSenderService
    extends Service
{

    private final static URL SOAPTOJMSSENDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPTOJMSSENDERSERVICE_EXCEPTION;
    private final static QName SOAPTOJMSSENDERSERVICE_QNAME = new QName("http://soap2jms.github.com/service", "soapToJmsSenderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/usr/local/prj/misc/soap2jms/s2j_common/src/main/resources/queueSender.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPTOJMSSENDERSERVICE_WSDL_LOCATION = url;
        SOAPTOJMSSENDERSERVICE_EXCEPTION = e;
    }

    public SoapToJmsSenderService() {
        super(__getWsdlLocation(), SOAPTOJMSSENDERSERVICE_QNAME);
    }

    public SoapToJmsSenderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPTOJMSSENDERSERVICE_QNAME, features);
    }

    public SoapToJmsSenderService(URL wsdlLocation) {
        super(wsdlLocation, SOAPTOJMSSENDERSERVICE_QNAME);
    }

    public SoapToJmsSenderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPTOJMSSENDERSERVICE_QNAME, features);
    }

    public SoapToJmsSenderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapToJmsSenderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SenderSoap2Jms
     */
    @WebEndpoint(name = "senderSOAP")
    public SenderSoap2Jms getSenderSOAP() {
        return super.getPort(new QName("http://soap2jms.github.com/service", "senderSOAP"), SenderSoap2Jms.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SenderSoap2Jms
     */
    @WebEndpoint(name = "senderSOAP")
    public SenderSoap2Jms getSenderSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap2jms.github.com/service", "senderSOAP"), SenderSoap2Jms.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPTOJMSSENDERSERVICE_EXCEPTION!= null) {
            throw SOAPTOJMSSENDERSERVICE_EXCEPTION;
        }
        return SOAPTOJMSSENDERSERVICE_WSDL_LOCATION;
    }

}
