
package com.github.soap2jms.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "soapToJmsReaderService", targetNamespace = "http://soap2jms.github.com/service", wsdlLocation = "file:/usr/local/prj/misc/soap2jms/s2j_common/src/main/resources/queueReader.wsdl")
public class SoapToJmsReaderService extends Service {

	private final static QName SOAPTOJMSREADERSERVICE_QNAME = new QName("http://soap2jms.github.com/service",
			"soapToJmsReaderService");

	public SoapToJmsReaderService(final String wsdlLocation) throws MalformedURLException {
		super(new URL(wsdlLocation), SOAPTOJMSREADERSERVICE_QNAME);
	}

	public SoapToJmsReaderService(final URL wsdlLocation) {
		super(wsdlLocation, SOAPTOJMSREADERSERVICE_QNAME);
	}

	public SoapToJmsReaderService(final URL wsdlLocation, final QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SoapToJmsReaderService(final URL wsdlLocation, final QName serviceName,
			final WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	public SoapToJmsReaderService(final URL wsdlLocation, final WebServiceFeature... features) {
		super(wsdlLocation, SOAPTOJMSREADERSERVICE_QNAME, features);
	}

	/**
	 * 
	 * @return returns ReaderSoap2Jms
	 */
	@WebEndpoint(name = "readerSOAP")
	public ReaderSoap2Jms getReaderSOAP() {
		return super.getPort(new QName("http://soap2jms.github.com/service", "readerSOAP"), ReaderSoap2Jms.class);
	}

}
