
package com.github.soap2jms.reader;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.github.soap2jms.reader.common.ws.MessageIdAndStatus;
import com.github.soap2jms.reader.common.ws.ObjectFactory;
import com.github.soap2jms.reader.common.ws.RetrieveMessageResponseType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "reader.soap2jms", targetNamespace = "http://soap2jms.github.com/reader")
@XmlSeeAlso({ ObjectFactory.class })
public interface ReaderSoap2Jms {

	/**
	 * 
	 * @param messageId
	 * @return returns
	 *         java.util.List<com.github.soap2jms.reader.common.ws.MessageIdAndStatus>
	 * @throws S2JmsException
	 */
	@WebMethod(action = "http://soap2jms.github.com/acknowledgeMessages")
	@WebResult(name = "messageIdAndStatus", targetNamespace = "")
	@RequestWrapper(localName = "acknowledgeMessages", targetNamespace = "http://soap2jms.github.com/reader/common/ws", className = "com.github.soap2jms.reader.common.ws.AcknowledgeMessages")
	@ResponseWrapper(localName = "acknowledgeMessagesResponse", targetNamespace = "http://soap2jms.github.com/reader/common/ws", className = "com.github.soap2jms.reader.common.ws.AcknowledgeMessagesResponse")
	public List<MessageIdAndStatus> acknowledgeMessages(
			@WebParam(name = "messageId", targetNamespace = "") List<String> messageId) throws S2JmsException;

	/**
	 * 
	 * @param filter
	 * @param maxItems
	 * @param queueName
	 * @return returns
	 *         com.github.soap2jms.reader.common.ws.RetrieveMessageResponseType
	 * @throws S2JmsException
	 */
	@WebMethod(action = "http://soap2jms.github.com/retrieveMessages")
	@WebResult(name = "retrieveMessagesResponse", targetNamespace = "")
	@RequestWrapper(localName = "retrieveMessages", targetNamespace = "http://soap2jms.github.com/reader/common/ws", className = "com.github.soap2jms.reader.common.ws.RetrieveMessages")
	@ResponseWrapper(localName = "retrieveMessagesResponse", targetNamespace = "http://soap2jms.github.com/reader/common/ws", className = "com.github.soap2jms.reader.common.ws.RetrieveMessagesResponse")
	public RetrieveMessageResponseType retrieveMessages(
			@WebParam(name = "queueName", targetNamespace = "") String queueName,
			@WebParam(name = "filter", targetNamespace = "") String filter,
			@WebParam(name = "maxItems", targetNamespace = "") int maxItems) throws S2JmsException;

}
