
package com.github.soap2jms.reader;

import javax.xml.ws.WebFault;
import com.github.soap2jms.reader.common.ws.S2JmsExceptionType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "s2jmsException", targetNamespace = "http://soap2jms.github.com/reader/common/ws")
public class S2JmsException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private S2JmsExceptionType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public S2JmsException(String message, S2JmsExceptionType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public S2JmsException(String message, S2JmsExceptionType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.github.soap2jms.reader.common.ws.S2JmsExceptionType
     */
    public S2JmsExceptionType getFaultInfo() {
        return faultInfo;
    }

}
