
package com.github.soap2jms.reader;

import javax.xml.ws.WebFault;

import com.github.soap2jms.reader.common.WsExceptionClass;
import com.github.soap2jms.reader.common.ws.WsJmsExceptionData;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "wsJmsException", targetNamespace = "http://soap2jms.github.com/reader/common/ws")
public class WsJmsException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7206025596739273285L;
	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private WsJmsExceptionData faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public WsJmsException(String message, WsJmsExceptionData faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public WsJmsException(String message, String originalException, 
			Integer code, WsExceptionClass exceptionType) {
		super(message);
		this.faultInfo = new WsJmsExceptionData(message, originalException, code, null, exceptionType);
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public WsJmsException(String message, WsJmsExceptionData faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         com.github.soap2jms.reader.common.ws.WsJmsExceptionData
	 */
	public WsJmsExceptionData getFaultInfo() {
		return faultInfo;
	}

}
