package com.github.soap2jms.reader;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-18T11:20:50.120+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "jmsReaderSoap", 
                  wsdlLocation = "file:/usr/local/prj/misc/workspace/test/reader_common/src/main/resources/queueReader.wsdl",
                  targetNamespace = "http://soap2jms.github.com/reader") 
public class JmsReaderSoap extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap2jms.github.com/reader", "jmsReaderSoap");
    public final static QName ReaderSOAP = new QName("http://soap2jms.github.com/reader", "readerSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/usr/local/prj/misc/workspace/test/reader_common/src/main/resources/queueReader.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JmsReaderSoap.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/usr/local/prj/misc/workspace/test/reader_common/src/main/resources/queueReader.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JmsReaderSoap(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JmsReaderSoap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JmsReaderSoap() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public JmsReaderSoap(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public JmsReaderSoap(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public JmsReaderSoap(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ReaderSoap2JmsGithubCom
     */
    @WebEndpoint(name = "readerSOAP")
    public ReaderSoap2JmsGithubCom getReaderSOAP() {
        return super.getPort(ReaderSOAP, ReaderSoap2JmsGithubCom.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReaderSoap2JmsGithubCom
     */
    @WebEndpoint(name = "readerSOAP")
    public ReaderSoap2JmsGithubCom getReaderSOAP(WebServiceFeature... features) {
        return super.getPort(ReaderSOAP, ReaderSoap2JmsGithubCom.class, features);
    }

}
