package com.github.soap2jms.reader;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-09-18T11:20:50.110+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://soap2jms.github.com/reader", name = "reader.soap2jms.github.com")
@XmlSeeAlso({com.github.soap2jms.reader_common.ObjectFactory.class})
public interface ReaderSoap2JmsGithubCom {

    @WebMethod(action = "http://soap2jms.github.com/retrieveMessages")
    @RequestWrapper(localName = "retrieveMessages", targetNamespace = "http://soap2jms.github.com/reader_common", className = "com.github.soap2jms.reader_common.RetrieveMessages")
    @ResponseWrapper(localName = "retrieveMessagesResponse", targetNamespace = "http://soap2jms.github.com/reader_common", className = "com.github.soap2jms.reader_common.RetrieveMessagesResponse")
    @WebResult(name = "retrieveMessagesResponse", targetNamespace = "")
    public com.github.soap2jms.reader_common.RetrieveMessageResponseType retrieveMessages(
        @WebParam(name = "filter", targetNamespace = "")
        java.lang.String filter,
        @WebParam(name = "maxItems", targetNamespace = "")
        int maxItems
    );

    @WebMethod(action = "http://soap2jms.github.com/acknowledgeMessages")
    @RequestWrapper(localName = "acknowledgeMessages", targetNamespace = "http://soap2jms.github.com/reader_common", className = "com.github.soap2jms.reader_common.AcknowledgeMessages")
    @ResponseWrapper(localName = "acknowledgeMessagesResponse", targetNamespace = "http://soap2jms.github.com/reader_common", className = "com.github.soap2jms.reader_common.AcknowledgeMessagesResponse")
    @WebResult(name = "messageIdAndStatus", targetNamespace = "")
    public java.util.List<com.github.soap2jms.reader_common.MessageIdAndStatus> acknowledgeMessages(
        @WebParam(name = "messageId", targetNamespace = "")
        java.util.List<java.lang.String> messageId
    );
}
